name = "template-shop-auth"
main = "worker.js"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "KEY_BINDINGS"
id = "d9506c098eda4702978c2298fcc3810d"

[[kv_namespaces]]
binding = "KEY_STORE"
id = "a805d5fd6bf44be9a030e33afb7529c6"

[vars]
ENVIRONMENT = "production"
